from dataclasses import dataclass
from typing import List, Set, Dict


@dataclass
class LanguageConfig:
    package: str
    entities: Set[str]
    body_fields: List[str]
    fallback_bodies: Set[str]
    stub_suffix: str
    canonical_map: Dict[str, str]  # Maps raw type -> MODULE/CLASS/FUNCTION
    language_function: str = "language"


LANGUAGE_MAP: Dict[str, LanguageConfig] = {
    "python": LanguageConfig(
        package="tree_sitter_python",
        entities={"class_definition", "function_definition"},
        body_fields=["body"],
        fallback_bodies={"block"},
        stub_suffix=" ...",
        canonical_map={
            "class_definition": "CLASS",
            "function_definition": "FUNCTION",
        },
    ),
    "javascript": LanguageConfig(
        package="tree_sitter_javascript",
        entities={
            "class_declaration",
            "function_declaration",
            "method_definition",
            "arrow_function",
        },
        body_fields=["body"],
        fallback_bodies={"statement_block"},
        stub_suffix=" { ... }",
        canonical_map={
            "class_declaration": "CLASS",
            "function_declaration": "FUNCTION",
            "method_definition": "METHOD",
            "arrow_function": "FUNCTION",
        },
    ),
    "typescript": LanguageConfig(
        package="tree_sitter_typescript",
        entities={
            "class_declaration",
            "function_declaration",
            "method_definition",
            "arrow_function",
            "interface_declaration",
            "type_alias_declaration",
        },
        body_fields=["body"],
        fallback_bodies={"statement_block", "object_type"},
        stub_suffix=" { ... }",
        canonical_map={
            "class_declaration": "CLASS",
            "function_declaration": "FUNCTION",
            "method_definition": "METHOD",
            "arrow_function": "FUNCTION",
            "interface_declaration": "CLASS",
            "type_alias_declaration": "CLASS",
        },
        language_function="language_typescript",
    ),
    "java": LanguageConfig(
        package="tree_sitter_java",
        entities={
            "class_declaration",
            "method_declaration",
            "interface_declaration",
            "enum_declaration",
        },
        body_fields=["body"],
        fallback_bodies={"block"},
        stub_suffix=" { ... }",
        canonical_map={
            "class_declaration": "CLASS",
            "method_declaration": "METHOD",
            "interface_declaration": "CLASS",
            "enum_declaration": "CLASS",
        },
    ),
    "cpp": LanguageConfig(
        package="tree_sitter_cpp",
        entities={"class_specifier", "function_definition", "struct_specifier"},
        body_fields=["body"],
        fallback_bodies={"compound_statement"},
        stub_suffix=" { ... }",
        canonical_map={
            "class_specifier": "CLASS",
            "function_definition": "FUNCTION",
            "struct_specifier": "CLASS",
        },
    ),
    "c_sharp": LanguageConfig(
        package="tree_sitter_c_sharp",
        entities={
            "class_declaration",
            "method_declaration",
            "interface_declaration",
            "struct_declaration",
            "enum_declaration",
        },
        body_fields=["body"],
        fallback_bodies={"block"},
        stub_suffix=" { ... }",
        canonical_map={
            "class_declaration": "CLASS",
            "method_declaration": "METHOD",
            "interface_declaration": "CLASS",
            "struct_declaration": "CLASS",
            "enum_declaration": "CLASS",
        },
    ),
    "c": LanguageConfig(
        package="tree_sitter_c",
        entities={"function_definition", "struct_specifier"},
        body_fields=["body"],
        fallback_bodies={"compound_statement"},
        stub_suffix=" { ... }",
        canonical_map={
            "function_definition": "FUNCTION",
            "struct_specifier": "CLASS",
        },
    ),
    "go": LanguageConfig(
        package="tree_sitter_go",
        entities={"function_declaration", "method_declaration", "type_declaration"},
        body_fields=["body"],
        fallback_bodies={"block"},
        stub_suffix=" { ... }",
        canonical_map={
            "function_declaration": "FUNCTION",
            "method_declaration": "METHOD",
            "type_declaration": "CLASS",
        },
    ),
    "rust": LanguageConfig(
        package="tree_sitter_rust",
        entities={
            "function_item",
            "struct_item",
            "enum_item",
            "trait_item",
            "impl_item",
        },
        body_fields=["body"],
        fallback_bodies={"block"},
        stub_suffix=" { ... }",
        canonical_map={
            "function_item": "FUNCTION",
            "struct_item": "CLASS",
            "enum_item": "CLASS",
            "trait_item": "CLASS",
            "impl_item": "CLASS",
        },
    ),
    "php": LanguageConfig(
        package="tree_sitter_php",
        entities={
            "class_declaration",
            "function_definition",
            "method_declaration",
            "interface_declaration",
            "trait_declaration",
        },
        body_fields=["body"],
        fallback_bodies={"compound_statement"},
        stub_suffix=" { ... }",
        canonical_map={
            "class_declaration": "CLASS",
            "function_definition": "FUNCTION",
            "method_declaration": "METHOD",
            "interface_declaration": "CLASS",
            "trait_declaration": "CLASS",
        },
    ),
    "ruby": LanguageConfig(
        package="tree_sitter_ruby",
        entities={"class", "method", "module", "singleton_method"},
        body_fields=["body"],
        fallback_bodies={"do_block", "block"},
        stub_suffix=" ... end",
        canonical_map={
            "class": "CLASS",
            "method": "METHOD",
            "module": "MODULE",
            "singleton_method": "METHOD",
        },
    ),
    "swift": LanguageConfig(
        package="tree_sitter_swift",
        entities={
            "class_declaration",
            "function_declaration",
            "struct_declaration",
            "protocol_declaration",
            "enum_declaration",
        },
        body_fields=["body"],
        fallback_bodies={"code_block"},
        stub_suffix=" { ... }",
        canonical_map={
            "class_declaration": "CLASS",
            "function_declaration": "FUNCTION",
            "struct_declaration": "CLASS",
            "protocol_declaration": "CLASS",
            "enum_declaration": "CLASS",
        },
    ),
    "kotlin": LanguageConfig(
        package="tree_sitter_kotlin",
        entities={
            "class_declaration",
            "function_declaration",
            "object_declaration",
            "interface_declaration",
        },
        body_fields=["body"],
        fallback_bodies={"function_body", "class_body"},
        stub_suffix=" { ... }",
        canonical_map={
            "class_declaration": "CLASS",
            "function_declaration": "METHOD",
            "object_declaration": "CLASS",
            "interface_declaration": "CLASS",
        },
    ),
    "sql": LanguageConfig(
        package="tree_sitter_sql",
        entities={
            "create_table_statement",
            "create_view_statement",
            "create_function_statement",
            "create_procedure_statement",
        },
        body_fields=["body"],
        fallback_bodies={"block"},
        stub_suffix=" ...",
        canonical_map={
            "create_table_statement": "CLASS",
            "create_view_statement": "CLASS",
            "create_function_statement": "FUNCTION",
            "create_procedure_statement": "FUNCTION",
        },
    ),
    "bash": LanguageConfig(
        package="tree_sitter_bash",
        entities={"function_definition"},
        body_fields=["body"],
        fallback_bodies={"compound_statement"},
        stub_suffix=" { ... }",
        canonical_map={
            "function_definition": "FUNCTION",
        },
    ),
    "r": LanguageConfig(
        package="tree_sitter_r",
        entities={"function_definition"},
        body_fields=["body"],
        fallback_bodies={"braced_expression"},
        stub_suffix=" { ... }",
        canonical_map={
            "function_definition": "FUNCTION",
        },
    ),
    "dart": LanguageConfig(
        package="tree_sitter_dart",
        entities={"class_definition", "function_declaration", "method_declaration"},
        body_fields=["body"],
        fallback_bodies={"function_body"},
        stub_suffix=" { ... }",
        canonical_map={
            "class_definition": "CLASS",
            "function_declaration": "FUNCTION",
            "method_declaration": "METHOD",
        },
    ),
    "scala": LanguageConfig(
        package="tree_sitter_scala",
        entities={
            "class_definition",
            "function_definition",
            "object_definition",
            "trait_definition",
        },
        body_fields=["body"],
        fallback_bodies={"template_body", "block"},
        stub_suffix=" { ... }",
        canonical_map={
            "class_definition": "CLASS",
            "function_definition": "METHOD",
            "object_definition": "CLASS",
            "trait_definition": "CLASS",
        },
    ),
    "lua": LanguageConfig(
        package="tree_sitter_lua",
        entities={
            "function_definition",
            "local_function_definition",
            "table_constructor",
        },
        body_fields=["body"],
        fallback_bodies={"block"},
        stub_suffix=" ... end",
        canonical_map={
            "function_definition": "FUNCTION",
            "local_function_definition": "FUNCTION",
            "table_constructor": "CLASS",
        },
    ),
    "perl": LanguageConfig(
        package="tree_sitter_perl",
        entities={"subroutine_definition"},
        body_fields=["body"],
        fallback_bodies={"block"},
        stub_suffix=" { ... }",
        canonical_map={
            "subroutine_definition": "FUNCTION",
        },
    ),
    "haskell": LanguageConfig(
        package="tree_sitter_haskell",
        entities={
            "function_declaration",
            "data_declaration",
            "newtype_declaration",
            "type_declaration",
        },
        body_fields=["body"],
        fallback_bodies={"exp_apply"},
        stub_suffix=" = ...",
        canonical_map={
            "function_declaration": "FUNCTION",
            "data_declaration": "CLASS",
            "newtype_declaration": "CLASS",
            "type_declaration": "CLASS",
        },
    ),
    "objective_c": LanguageConfig(
        package="tree_sitter_objc",
        entities={
            "class_interface",
            "class_implementation",
            "category_interface",
            "category_implementation",
            "function_definition",
            "method_definition",
        },
        body_fields=["body"],
        fallback_bodies={"compound_statement"},
        stub_suffix=" { ... }",
        canonical_map={
            "class_interface": "CLASS",
            "class_implementation": "CLASS",
            "category_interface": "CLASS",
            "category_implementation": "CLASS",
            "function_definition": "FUNCTION",
            "method_definition": "METHOD",
        },
    ),
    "zig": LanguageConfig(
        package="tree_sitter_zig",
        entities={"function_declaration", "struct_declaration"},
        body_fields=["body"],
        fallback_bodies={"block"},
        stub_suffix=" { ... }",
        canonical_map={
            "function_declaration": "FUNCTION",
            "struct_declaration": "CLASS",
        },
    ),
    "elixir": LanguageConfig(
        package="tree_sitter_elixir",
        entities={"call"},
        body_fields=["body"],
        fallback_bodies={"do_block"},
        stub_suffix=" do ... end",
        canonical_map={
            "call": "FUNCTION",
        },
    ),
    "julia": LanguageConfig(
        package="tree_sitter_julia",
        entities={"function_definition", "struct_definition", "module_definition"},
        body_fields=["body"],
        fallback_bodies={"block"},
        stub_suffix=" ... end",
        canonical_map={
            "function_definition": "FUNCTION",
            "struct_definition": "CLASS",
            "module_definition": "MODULE",
        },
    ),
}


EXTENSION_TO_LANGUAGE: Dict[str, str] = {
    ".py": "python",
    ".js": "javascript",
    ".jsx": "javascript",
    ".ts": "typescript",
    ".tsx": "typescript",
    ".java": "java",
    ".cpp": "cpp",
    ".hpp": "cpp",
    ".cc": "cpp",
    ".hh": "cpp",
    ".c": "c",
    ".h": "c",
    ".cs": "c_sharp",
    ".go": "go",
    ".rs": "rust",
    ".php": "php",
    ".rb": "ruby",
    ".swift": "swift",
    ".kt": "kotlin",
    ".kts": "kotlin",
    ".sql": "sql",
    ".sh": "bash",
    ".bash": "bash",
    ".r": "r",
    ".dart": "dart",
    ".scala": "scala",
    ".lua": "lua",
    ".pl": "perl",
    ".pm": "perl",
    ".hs": "haskell",
    ".m": "objective_c",
    ".mm": "objective_c",
    ".zig": "zig",
    ".ex": "elixir",
    ".exs": "elixir",
    ".jl": "julia",
}
